// AUTO-GENERATED by scripts/chain-sync.mjs from contracts/out (IChargeMeshEscrow). Do not edit.
export const chargeMeshEscrowAbi = [
  {
    "type": "function",
    "name": "SETTLEMENT_GRACE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cancel",
    "inputs": [
      {
        "name": "reservationId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "expire",
    "inputs": [
      {
        "name": "reservationId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getReservation",
    "inputs": [
      {
        "name": "reservationId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IChargeMeshEscrow.Reservation",
        "components": [
          {
            "name": "slotRef",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "driver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "host",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "requestedWh",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "deliveredWh",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "pricePerKwhWei",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "depositWei",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "startTime",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "endTime",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum IChargeMeshEscrow.Status"
          },
          {
            "name": "sessionHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hashQuote",
    "inputs": [
      {
        "name": "quote",
        "type": "tuple",
        "internalType": "struct IChargeMeshEscrow.ReservationQuote",
        "components": [
          {
            "name": "reservationId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "slotRef",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "driver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "host",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "requestedWh",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "pricePerKwhWei",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "depositWei",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "startTime",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "endTime",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "quoteExpiry",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isSlotTaken",
    "inputs": [
      {
        "name": "slotRef",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "reserve",
    "inputs": [
      {
        "name": "quote",
        "type": "tuple",
        "internalType": "struct IChargeMeshEscrow.ReservationQuote",
        "components": [
          {
            "name": "reservationId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "slotRef",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "driver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "host",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "requestedWh",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "pricePerKwhWei",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "depositWei",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "startTime",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "endTime",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "quoteExpiry",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "setSettler",
    "inputs": [
      {
        "name": "newSettler",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settle",
    "inputs": [
      {
        "name": "reservationId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "deliveredWh",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "sessionHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settler",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "startSession",
    "inputs": [
      {
        "name": "reservationId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "ReservationCancelled",
    "inputs": [
      {
        "name": "reservationId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "refundWei",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReservationCreated",
    "inputs": [
      {
        "name": "reservationId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "slotRef",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "driver",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "host",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "requestedWh",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "pricePerKwhWei",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "depositWei",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "startTime",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "endTime",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReservationExpired",
    "inputs": [
      {
        "name": "reservationId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "refundWei",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReservationSettled",
    "inputs": [
      {
        "name": "reservationId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "deliveredWh",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "billableWh",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "hostAmountWei",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "refundWei",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "sessionHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SessionStarted",
    "inputs": [
      {
        "name": "reservationId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "startedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SettlerUpdated",
    "inputs": [
      {
        "name": "previousSettler",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newSettler",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "IncorrectDeposit",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidQuote",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidStatus",
    "inputs": [
      {
        "name": "current",
        "type": "uint8",
        "internalType": "enum IChargeMeshEscrow.Status"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotDriver",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotSettler",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuoteExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReservationExists",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SlotAlreadyTaken",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TooEarly",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TooLate",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroSessionHash",
    "inputs": []
  }
] as const;
