// AUTO-GENERATED by scripts/chain-sync.mjs from contracts/deployments/*.json. Do not edit.
import type { Deployment } from "./types";

export const deployments: Partial<Record<number, Deployment>> = {
};
