#!/usr/bin/env node
// Generates src/chain/abi.ts and src/chain/deployments.ts from Foundry output.
// Run `forge build` (WSL) first. Owner: blockchain team. See docs/04-akilli-sozlesme.md.
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contractsDir = resolve(here, "../../contracts");
const chainDir = resolve(here, "../src/chain");

const candidates = [
  join(contractsDir, "out/ChargeMeshEscrow.sol/ChargeMeshEscrow.json"),
  join(contractsDir, "out/IChargeMeshEscrow.sol/IChargeMeshEscrow.json"),
];
const artifactPath = candidates.find((p) => existsSync(p));
if (!artifactPath) {
  console.error("No Foundry artifact found. Run `forge build` in contracts/ (WSL) first.");
  process.exit(1);
}

const { abi } = JSON.parse(readFileSync(artifactPath, "utf8"));
const source = artifactPath.includes("IChargeMeshEscrow") ? "IChargeMeshEscrow" : "ChargeMeshEscrow";
writeFileSync(
  join(chainDir, "abi.ts"),
  `// AUTO-GENERATED by scripts/chain-sync.mjs from contracts/out (${source}). Do not edit.\n` +
    `export const chargeMeshEscrowAbi = ${JSON.stringify(abi, null, 2)} as const;\n`,
);

const deploymentsDir = join(contractsDir, "deployments");
const entries = existsSync(deploymentsDir)
  ? readdirSync(deploymentsDir)
      .filter((f) => /^\d+\.json$/.test(f))
      .map((f) => JSON.parse(readFileSync(join(deploymentsDir, f), "utf8")))
      .sort((a, b) => a.chainId - b.chainId)
  : [];

const body = entries
  .map(
    (d) =>
      `  ${d.chainId}: {\n    chainId: ${d.chainId},\n    escrow: "${d.escrow}",\n    settler: "${d.settler}",\n    deployBlock: ${d.deployBlock}n,\n  },`,
  )
  .join("\n");
writeFileSync(
  join(chainDir, "deployments.ts"),
  `// AUTO-GENERATED by scripts/chain-sync.mjs from contracts/deployments/*.json. Do not edit.\n` +
    `import type { Deployment } from "./types";\n\n` +
    `export const deployments: Partial<Record<number, Deployment>> = {\n${body}${body ? "\n" : ""}};\n`,
);

console.log(`abi.ts <- ${source} (${abi.length} items)`);
console.log(`deployments.ts <- ${entries.length} deployment(s)`);
