// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {ECDSA} from "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";

import {ChargeMeshEscrow} from "../src/ChargeMeshEscrow.sol";
import {IChargeMeshEscrow} from "../src/interfaces/IChargeMeshEscrow.sol";

/// @dev Exposes the internal signer check for testing.
contract ChargeMeshEscrowSignerHarness is ChargeMeshEscrow {
    constructor(address initialOwner, address initialSettler) ChargeMeshEscrow(initialOwner, initialSettler) {}

    function exposedVerifyQuoteSigner(ReservationQuote calldata quote, bytes calldata signature) external view {
        _verifyQuoteSigner(quote, signature);
    }
}

// test/fixtures/quote-signature.json is generated by
// `corepack pnpm --filter @chargemesh/shared fixture:quote` (shared/scripts/gen-quote-fixture.ts).
// Never edit it by hand.

/// @notice TS <-> Solidity EIP-712 compatibility guard.
/// @dev If this test fails, the TypeScript and Solidity typed-data definitions diverged.
contract Eip712CompatTest is Test {
    string internal json;
    uint256 internal chainId;
    address internal verifyingContract;
    address internal fixtureSettler;
    bytes32 internal digest;
    bytes internal signature;
    IChargeMeshEscrow.ReservationQuote internal quote;
    ChargeMeshEscrow internal escrow;

    function setUp() public {
        json = vm.readFile(string.concat(vm.projectRoot(), "/test/fixtures/quote-signature.json"));

        chainId = vm.parseJsonUint(json, ".chainId");
        verifyingContract = vm.parseJsonAddress(json, ".verifyingContract");
        fixtureSettler = vm.parseJsonAddress(json, ".settler");
        digest = vm.parseJsonBytes32(json, ".digest");
        signature = vm.parseJsonBytes(json, ".signature");

        quote = IChargeMeshEscrow.ReservationQuote({
            reservationId: vm.parseJsonBytes32(json, ".quote.reservationId"),
            slotRef: vm.parseJsonBytes32(json, ".quote.slotRef"),
            driver: vm.parseJsonAddress(json, ".quote.driver"),
            host: vm.parseJsonAddress(json, ".quote.host"),
            requestedWh: uint32(vm.parseJsonUint(json, ".quote.requestedWh")),
            pricePerKwhWei: uint128(vm.parseJsonUint(json, ".quote.pricePerKwhWei")),
            depositWei: uint128(vm.parseJsonUint(json, ".quote.depositWei")),
            startTime: uint64(vm.parseJsonUint(json, ".quote.startTime")),
            endTime: uint64(vm.parseJsonUint(json, ".quote.endTime")),
            quoteExpiry: uint64(vm.parseJsonUint(json, ".quote.quoteExpiry"))
        });

        vm.chainId(chainId);
        deployCodeTo(
            "ChargeMeshEscrow.sol:ChargeMeshEscrow", abi.encode(address(this), fixtureSettler), verifyingContract
        );
        escrow = ChargeMeshEscrow(verifyingContract);
    }

    function test_fixtureSanity() public view {
        assertEq(block.chainid, chainId);
        assertEq(address(escrow), verifyingContract);
        assertEq(escrow.settler(), fixtureSettler);
        // Guard against silent truncation of the uint casts above.
        assertEq(uint256(quote.depositWei), vm.parseJsonUint(json, ".quote.depositWei"));
        assertEq(uint256(quote.pricePerKwhWei), vm.parseJsonUint(json, ".quote.pricePerKwhWei"));
    }

    function test_hashQuote_matchesTypeScriptDigest() public view {
        assertEq(escrow.hashQuote(quote), digest, "EIP-712 digest mismatch between TS and Solidity");
    }

    function test_signature_recoversSettler() public view {
        assertEq(ECDSA.recover(digest, signature), fixtureSettler, "fixture signature does not recover settler");
        assertEq(ECDSA.recover(escrow.hashQuote(quote), signature), escrow.settler());
    }

    function test_verifyQuoteSigner_acceptsFixtureSignature() public {
        ChargeMeshEscrowSignerHarness h = _deployHarness(fixtureSettler);
        h.exposedVerifyQuoteSigner(quote, signature); // must not revert
    }

    function test_verifyQuoteSigner_rejectsOtherSettler() public {
        ChargeMeshEscrowSignerHarness h = _deployHarness(makeAddr("otherSettler"));
        vm.expectRevert(IChargeMeshEscrow.InvalidSignature.selector);
        h.exposedVerifyQuoteSigner(quote, signature);
    }

    function test_verifyQuoteSigner_rejectsTamperedQuote() public {
        ChargeMeshEscrowSignerHarness h = _deployHarness(fixtureSettler);
        IChargeMeshEscrow.ReservationQuote memory tampered = quote;
        tampered.pricePerKwhWei += 1;
        vm.expectRevert(IChargeMeshEscrow.InvalidSignature.selector);
        h.exposedVerifyQuoteSigner(tampered, signature);
    }

    function test_hashQuote_dependsOnChainId() public {
        vm.chainId(chainId + 1);
        assertTrue(escrow.hashQuote(quote) != digest);
    }

    function _deployHarness(address settler_) internal returns (ChargeMeshEscrowSignerHarness) {
        deployCodeTo(
            "Eip712Compat.t.sol:ChargeMeshEscrowSignerHarness", abi.encode(address(this), settler_), verifyingContract
        );
        return ChargeMeshEscrowSignerHarness(verifyingContract);
    }
}
