// AUTO-GENERATED by scripts/chain-sync.mjs from contracts/deployments/*.json. Do not edit.
import type { Deployment } from "./types";

export const deployments: Partial<Record<number, Deployment>> = {
  10143: {
    chainId: 10143,
    escrow: "0x2541cA7961fdBE38446b8081e7B92136dAE770cf",
    settler: "0x10562C789bB833c1930cdc7115D4fC0C4D32BA73",
    deployBlock: 65835872n,
  },
};
